#Importar algumas bibliotecas
import streamlit as st

#*********************************Início da APP**********************************************************************************************************************************************************************************************************************************************************************

#Título:
st.title("Um dia na História")
#Saudação inicial
st.write("Bem vinda, Maria!")
#Estabelecer o dia:
st.header("3 de setembro")
st.write("O dia 3 de setembro é uma data histórica: foi no 246º dia do calendário gregoriano (247º em anos bissextos) que se deram vários acontecimentos históricos de grande relevo.")
#Estabelecer a categoria de acontecimentos
with st.sidebar:
    st.markdown("**Tipos de acontecimentos a visualizar:**")
    EventosHistóricos = st.toggle("Eventos Históricos")
    Nascimentos = st.toggle("Nascimentos")
    Mortes = st.toggle("Mortes")
    condition = True #Uma variável que permite interromper o código, para que não exista repetição de dados apresentados.

#Eventos históricos:
if EventosHistóricos:
    st.subheader("Principais Eventos Históricos" , divider= "rainbow")
    #Estabelecer que épocas evidenciar
    with st.sidebar:
        st.markdown("**Por favor selecione as principais épocas a visualizar:**")
        SeculosAntesDeCristo = st.toggle("Séculos antes de Cristo (a.C.)")              #a.C.
        SeculoIaXI = st.toggle("Século I a século XI")                                  #I a XI
        SeculoXIIaXIX = st.toggle("Século XII a seculo XIX")                            #XII a XIX
        SeculoXX = st.toggle("Século XX")                                               #XX
        SeculoXXI = st.toggle("Século XXI")                                             #XXI
        TodasAsEpocas = st.toggle("Todas as épocas")                                    #Todas
    if TodasAsEpocas:
        condition = False
        st.markdown("")
        st.subheader("36 a.C. :")
        st.markdown("Na *Batalha de Nauloco*, ***Marco Vipsânio Agripa***, almirante de ***Otávio***, derrota ***Sexto Pompeu***, filho de ***Pompeo***, terminando assim a resistência pompeana ao *Segundo Triunvirato*.")
        st.image("nauloco.jpg", caption="Batalha de Nauloco")
        st.subheader("301:")
        st.markdown("***San Marino***, um dos mais pequenos países do mundo, e a república mais antiga ainda existente, é fundada por *São Marino*.")
        st.image("sanmarino.jpg" , caption="Bandeira de San Marino")
        st.subheader("590:")
        st.markdown("O ***Papa Gregório I***, ou *São Gregório Magnum*, é eleito.")
        st.image("gregorio.jpg" , caption="Papa Gregório I")
        st.subheader("673:")
        st.markdown("O Rei ***Vamba*** dos *Visigodos* reprime uma revolta de ***Hilderico***, governador de *Nimes* e rival ao trono.")
        st.image("vamba.jpg" , caption="A coroação do Rei Vamba")
        st.subheader("863:")
        st.markdown("Maior vitória bizantina na ***Batlha de Lalacão*** contra uma ataque árabe.")
        st.image("lalacao.jpg" , caption="Batlha de Lalacão")
        st.subheader("1189:")
        st.markdown("Coroação de ***Ricardo I*** de *Inglaterra*.")
        st.image("ricardo.jpg" , caption="Coroação de Ricardo I de Inglaterra")
        st.subheader("1260:")
        st.markdown("Os *mamelucos* derrotam os *mongóis* na ***Batalha de Ain Jalut*** na *Palestina*, marcando a sua primeira derrota decisiva e o ponto de máxima expansão do *Império Mongol*.")
        st.image("ainjalut.jpg" , caption="Batalha de Ain Jalut")
        st.subheader("1335:")
        st.markdown("No *Congresso de Visegrád*, ***Carlos I da Hungria*** media uma reconciliação entre dois monarcas vizinhos, ***João da Boêmia*** e ***Casemiro III da Polónia***.")
        st.image("carlosI.jpg" , caption="Carlos I")
        st.subheader("1384:")
        st.markdown("Levamtamento do ***Cerco de Lisboa*** devido, sobretudo, à *Peste Negra*, que assolava o exército castelhano.")
        st.image("lisboa.jpg" , caption="Cerco a Lisboa de 1384")
        st.subheader("1411:")
        st.markdown("É celebrado o ***Tratado de Selymbria*** entre o *Império Otomano* e a *República de Veneza*.")
        st.image("selymbria.jpg" , caption="Tratado de Selymbria")
        st.subheader("1650:")
        st.markdown("A vitória sobre os monarquistas, na ***Batalha de Dunbar*** abre o caminho para *Edinburgh* para o **Novo Exército Modelo** na *Terceira Guerra Civil Inglesa*.")
        st.image("dunbar.jpg" , caption="Batlha de Dunbar")
        st.subheader("1658:")
        st.markdown("Aquando da morte de ***Oliver Cromwell***, o seu filho, ***Richard Cromwell***, torna-se o *Lorde Protetor* de Inglaterra.")
        st.image("cromwell.jpg" , caption="Richard Cromwell")
        st.subheader("1666:")
        st.markdown("O *Royal Exchange* arde, no ***Grande Incêndio de Londres***.")
        st.image("incendio.jpg" , caption="O Grande Incêndio de Londres")
        st.subheader("1758:")
        st.markdown("*D. José I* escapa de uma tentativa de rgicídio, da qual resulta o ***Processo dos Távoras***.")
        st.image("tavoras.jpg" , caption="Execução pública dos Távoras")
        st.subheader("1759:")
        st.markdown("Expulsão dos ***jesuítas*** dos terristórios portugueses.")
        st.image("jesuitas.jpg")
        st.subheader("1783:")
        st.markdown("A ***Guerra da Independência dos Estados Unidos*** termina com a assinatura do *Tratado de Paris* pelos Estados Unidos e o Reino da Grã-Bretanha.")
        st.image("teaparty.jpg" , caption="Tea Party: o início da revolução americana")
        st.subheader("1843:")
        st.markdown("O rei ***Otto, da Grécia*** é forçado a conceder uma nova constituição após uma *revolta* em Atenas")
        st.image("otto.jpg" , caption="O rei Otto")
        st.subheader("1861:")
        st.markdown("Durante a *Guerra Civil Americana* o general confederado ***Leonidas Polk*** invade o neutro ***Kentucky***, fazendo com que a *legislatura estadual* pedisse a ajuda da ***União***.")
        st.image("confederados.jpg" , caption="Bandeira dos Estados Confederados da América")
        st.subheader("1870:")
        st.markdown("Durante a *Guerra Franco-Prussiana*** começa o ***Cerco de Metz***, que, mais tarde, viria a resultar numa vitória prussiana decisiva.")
        st.image("metz.jpg" , caption="Um dos fortes de Metz sobre ocupação alemã, após a rendição francesa")
        st.subheader("1914:")
        st.markdown("O ***Cardeal Giacomo della Chiesa*** é eleito *papa* e adota o nome de ***Bento XV***.")
        st.image("bento.jpg" , caption="O papa Bento XV")
        st.markdown("***Guilherme***, ***Príncipe da Albânia***, deixa o país após apenas seis meses de *reinado*, devido à opsição face ao seu governo.")
        st.image("guilherme.jpg" , caption="Guilherme,Prícipe da Albânia.")
        st.markdown("Durante ***A Primeira Guerra Mundial***, tem inícioa ***Batalha de Grand Couronné***: um assalto alemão contra as posições francesas em terreno elevado perto da cidade de *Nancy*.")
        st.image("couronne.jpg" , caption="Mapa dos vetores da Batalha de Grand Couronné.")
        st.subheader("1939:")
        st.markdown("A ***Segunda Guerra Mundial*** tem início quando a *França*, *Reino Unido*, *Nova Zelândia* e *Austrália* declaram guerra à *Alemanha* após a invasão da *Polónia*, formando os ***Aliados***.")
        st.image("paris.jpg" , caption="Fotografia que retrata Breker, Speer e Hitler em Paris, numa excurção de sensivelmente três horas após a capitulação francesa, a 23 de junho de 1940.")
        st.subheader("1941:")
        st.markdown("*Karl Fritzsch*, vice-comandante do ***Campo de Concentração de Auschwitz***, experimenta o uso de ***Zyklon B*** no gaseamento de prisioneiros de guerra soviéticos.")
        st.image("auschwitz.jpg" , caption="O Campo de Concentração de Auschwitz")
        st.subheader("1943:")
        st.markdown("Durante a ***Segunda Guerra Mundial*** a invasão *Aliada* da *Itália* começa no mesmo dia em que o general americano *Dwight D. Eisenhower* e o marechal italiano *Pietro Badoglio* assinam o ***Armistício de Cassibile*** a bordo do couroçado da *Royal Navy HMS Nelson")
        st.image("nelson.jpg" , caption="His Majesty's Ship (HMS) Nelson")
        st.subheader("1944:")
        st.markdown("***Anne Frank*** e a família são enviados no último comboio de transporte entre o ***Campo de Westerbork*** e o ***Campo de Concentração de Auschwitz***, chegando três dias depois.")
        st.image("annefrank.jpg" , caption="Anne Frank")
        st.subheader("1945:")
        st.markdown("Começa uma celebração de três dias na *China*, após o ***Dia da Vitória sobre o Japão***.")
        st.image("japao.jpg" , caption="Representantes japoneses chegam ao USS Missouri de forma a oficializar a rendição do seu país")
        st.subheader("1950:")
        st.markdown("*Nino* Farina torna-se o primeiro campeão de ***Formula 1*** depois de vencer o ***Grande Prémio de Itália***.")
        st.image("farina.jpg" , caption="Nino Farina no seu Formula")
        st.subheader("1954:")
        st.markdown("O ***Exército da Libertação Popular*** começa a bombardear as ilhas *Kinmen*, controladas pela *Républica da China*, dando início à ***Primeira Crise do Estreito de Taiwan***.")
        st.image("taiwan.jpg" , caption="A Ilha Formosa (Taiwan)")
        st.subheader("1967:")
        st.markdown("***Dagen H*** na *Suécia*: durante a noite, o tráfego muda de dirigir à esquerda para circular à direita.")
        st.image("autocarro.jpg")
        st.subheader("1971:")
        st.markdown("O ***Catar*** torna-se um estado independente.")
        st.image("catar.jpg" , caption="A bandeira catari")
        st.subheader("1976:")
        st.markdown("Integrando o programa *Viking*, a nave espacial ***Viking 2*** aterra na *Utopia Planitia*, em ***Marte***.")
        st.image("viking2.jpg" , caption="A nave espacial Viking 2")
        st.subheader("1981:")
        st.markdown("Instítuida pelas *Nações Unidas*, a ***Convenção sobre a eliminação de todas as formas de descriminação contra as mulheres***, uma declaração internacional de direitos das mulheres, entra em vigor.")
        st.image("nacoesunidas.jpg" , caption="Sala da Assembleia Geral da Organização das Nações Unidas, em Nova York")
        st.subheader("1987:")
        st.markdown("Durante um *Golpe de Estado*, o Presidente do *Burundi* ***Jean-Batptiste Bagaza*** é deposto pelo *major* ***Pierre Buyoya***.")
        st.image("bagaza.jpg" , caption="O Presidente deposto Jean-Baptiste Bagaza")
        st.subheader("1989:")
        st.markdown("O voo *Varig 254* faz uma aterragem de emrgência sobre uma região localizada a cerca de 60 Km a norte de *São José do Xingu, Mato Grosso, em consequência de falta de combustível; ***12 passageiros morreram.")
        st.image("varig.jpg" , caption="O avião envolvido no acidente, estacionado no Aeroporto Internacional do Rio de Janeiro-Galeão em outubro de 1983")
        st.subheader("1994:")
        st.markdown("Durante a ***Rutura sino-soviética***, a *Federação Russa* e a *Républica Popular da China* concordam em desalinhar as suas ***armas nucleares*** umas contra as outras.")
        st.image("mao.jpg" , caption="Mao e Stalin")
        st.subheader("1995:")
        st.markdown("O ***Ebay*** é fundado, nos *Estados Unidos+.")
        st.image("ebay.jpg" , caption="Logotipo do Ebay")
        st.subheader("2004:")
        st.markdown("Termina o ***cerco à escola de Beslan***, na *República Russa da Ossétia do Norte*, com, pelo menos, ***334 mortos***, a maioria crianças.")
        st.image("beslan.jpg" , caption="A escola do massacre de Beslan")
        st.subheader("2016:")
        st.markdown("Os ***EUA*** e a ***China***, juntos responsáveis por *40%* das emissões mundiais de carbono, ratificam formalmente o ***Acordo Climático Global de Paris***.")
        st.image("acordo.jpg")
        st.subheader("2017:")
        st.markdown("A *Coreia do Norte* conduz o seu sexto, e mais poderoso, ***teste nuclear***.")
        st.image("coreia.jpg" , caption="Teste nuclear efetuado pela Coreia do Norte em 2022")
    if SeculosAntesDeCristo and condition == True:
        st.markdown("")
        st.subheader("36 a.C. :")
        st.markdown("Na *Batalha de Nauloco*, ***Marco Vipsânio Agripa***, almirante de ***Otávio***, derrota ***Sexto Pompeu***, filho de ***Pompeo***, terminando assim a resistência pompeana ao *Segundo Triunvirato*.")
        st.image("nauloco.jpg", caption="Batalha de Nauloco")
    if SeculoIaXI and condition == True:
        st.subheader("301:")
        st.markdown("***San Marino***, um dos mais pequenos países do mundo, e a república mais antiga ainda existente, é fundada por *São Marino*.")
        st.image("sanmarino.jpg" , caption="Bandeira de San Marino")
        st.subheader("590:")
        st.markdown("O ***Papa Gregório I***, ou *São Gregório Magnum*, é eleito.")
        st.image("gregorio.jpg" , caption="Papa Gregório I")
        st.subheader("673:")
        st.markdown("O Rei ***Vamba*** dos *Visigodos* reprime uma revolta de ***Hilderico***, governador de *Nimes* e rival ao trono.")
        st.image("vamba.jpg" , caption="A coroação do Rei Vamba")
        st.subheader("863:")
        st.markdown("Maior vitória bizantina na ***Batlha de Lalacão*** contra uma ataque árabe.")
        st.image("lalacao.jpg" , caption="Batlha de Lalacão")
    if SeculoXIIaXIX and condition == True:
        st.subheader("1189:")
        st.markdown("Coroação de ***Ricardo I*** de *Inglaterra*.")
        st.image("ricardo.jpg" , caption="Coroação de Ricardo I de Inglaterra")
        st.subheader("1260:")
        st.markdown("Os *mamelucos* derrotam os *mongóis* na ***Batalha de Ain Jalut*** na *Palestina*, marcando a sua primeira derrota decisiva e o ponto de máxima expansão do *Império Mongol*.")
        st.image("ainjalut.jpg" , caption="Batalha de Ain Jalut")
        st.subheader("1335:")
        st.markdown("No *Congresso de Visegrád*, ***Carlos I da Hungria*** media uma reconciliação entre dois monarcas vizinhos, ***João da Boêmia*** e ***Casemiro III da Polónia***.")
        st.image("carlosI.jpg" , caption="Carlos I")
        st.subheader("1384:")
        st.markdown("Levamtamento do ***Cerco de Lisboa*** devido, sobretudo, à *Peste Negra*, que assolava o exército castelhano.")
        st.image("lisboa.jpg" , caption="Cerco a Lisboa de 1384")
        st.subheader("1411:")
        st.markdown("É celebrado o ***Tratado de Selymbria*** entre o *Império Otomano* e a *República de Veneza*.")
        st.image("selymbria.jpg" , caption="Tratado de Selymbria")
        st.subheader("1650:")
        st.markdown("A vitória sobre os monarquistas, na ***Batalha de Dunbar*** abre o caminho para *Edinburgh* para o **Novo Exército Modelo** na *Terceira Guerra Civil Inglesa*.")
        st.image("dunbar.jpg" , caption="Batlha de Dunbar")
        st.subheader("1658:")
        st.markdown("Aquando da morte de ***Oliver Cromwell***, o seu filho, ***Richard Cromwell***, torna-se o *Lorde Protetor* de Inglaterra.")
        st.image("cromwell.jpg" , caption="Richard Cromwell")
        st.subheader("1666:")
        st.markdown("O *Royal Exchange* arde, no ***Grande Incêndio de Londres***.")
        st.image("incendio.jpg" , caption="O Grande Incêndio de Londres")
        st.subheader("1758:")
        st.markdown("*D. José I* escapa de uma tentativa de rgicídio, da qual resulta o ***Processo dos Távoras***.")
        st.image("tavoras.jpg" , caption="Execução pública dos Távoras")
        st.subheader("1759:")
        st.markdown("Expulsão dos ***jesuítas*** dos terristórios portugueses.")
        st.image("jesuitas.jpg")
        st.subheader("1783:")
        st.markdown("A ***Guerra da Independência dos Estados Unidos*** termina com a assinatura do *Tratado de Paris* pelos Estados Unidos e o Reino da Grã-Bretanha.")
        st.image("teaparty.jpg" , caption="Tea Party: o início da revolução americana")
        st.subheader("1843:")
        st.markdown("O rei ***Otto, da Grécia*** é forçado a conceder uma nova constituição após uma *revolta* em Atenas")
        st.image("otto.jpg" , caption="O rei Otto")
        st.subheader("1861:")
        st.markdown("Durante a *Guerra Civil Americana* o general confederado ***Leonidas Polk*** invade o neutro ***Kentucky***, fazendo com que a *legislatura estadual* pedisse a ajuda da ***União***.")
        st.image("confederados.jpg" , caption="Bandeira dos Estados Confederados da América")
        st.subheader("1870:")
        st.markdown("Durante a *Guerra Franco-Prussiana*** começa o ***Cerco de Metz***, que, mais tarde, viria a resultar numa vitória prussiana decisiva.")
        st.image("metz.jpg" , caption="Um dos fortes de Metz sobre ocupação alemã, após a rendição francesa")
    if SeculoXX and condition == True:
        st.subheader("1914:")
        st.markdown("O ***Cardeal Giacomo della Chiesa*** é eleito *papa* e adota o nome de ***Bento XV***.")
        st.image("bento.jpg" , caption="O papa Bento XV")
        st.markdown("***Guilherme***, ***Príncipe da Albânia***, deixa o país após apenas seis meses de *reinado*, devido à opsição face ao seu governo.")
        st.image("guilherme.jpg" , caption="Guilherme,Prícipe da Albânia.")
        st.markdown("Durante ***A Primeira Guerra Mundial***, tem inícioa ***Batalha de Grand Couronné***: um assalto alemão contra as posições francesas em terreno elevado perto da cidade de *Nancy*.")
        st.image("couronne.jpg" , caption="Mapa dos vetores da Batalha de Grand Couronné.")
        st.subheader("1939:")
        st.markdown("A ***Segunda Guerra Mundial*** tem início quando a *França*, *Reino Unido*, *Nova Zelândia* e *Austrália* declaram guerra à *Alemanha* após a invasão da *Polónia*, formando os ***Aliados***.")
        st.image("paris.jpg" , caption="Fotografia que retrata Breker, Speer e Hitler em Paris, numa excurção de sensivelmente três horas após a capitulação francesa, a 23 de junho de 1940.")
        st.subheader("1941:")
        st.markdown("*Karl Fritzsch*, vice-comandante do ***Campo de Concentração de Auschwitz***, experimenta o uso de ***Zyklon B*** no gaseamento de prisioneiros de guerra soviéticos.")
        st.image("auschwitz.jpg" , caption="O Campo de Concentração de Auschwitz")
        st.subheader("1943:")
        st.markdown("Durante a ***Segunda Guerra Mundial*** a invasão *Aliada* da *Itália* começa no mesmo dia em que o general americano *Dwight D. Eisenhower* e o marechal italiano *Pietro Badoglio* assinam o ***Armistício de Cassibile*** a bordo do couroçado da *Royal Navy HMS Nelson")
        st.image("nelson.jpg" , caption="His Majesty's Ship (HMS) Nelson")
        st.subheader("1944:")
        st.markdown("***Anne Frank*** e a família são enviados no último comboio de transporte entre o ***Campo de Westerbork*** e o ***Campo de Concentração de Auschwitz***, chegando três dias depois.")
        st.image("annefrank.jpg" , caption="Anne Frank")
        st.subheader("1945:")
        st.markdown("Começa uma celebração de três dias na *China*, após o ***Dia da Vitória sobre o Japão***.")
        st.image("japao.jpg" , caption="Representantes japoneses chegam ao USS Missouri de forma a oficializar a rendição do seu país")
        st.subheader("1950:")
        st.markdown("*Nino* Farina torna-se o primeiro campeão de ***Formula 1*** depois de vencer o ***Grande Prémio de Itália***.")
        st.image("farina.jpg" , caption="Nino Farina no seu Formula")
        st.subheader("1954:")
        st.markdown("O ***Exército da Libertação Popular*** começa a bombardear as ilhas *Kinmen*, controladas pela *Républica da China*, dando início à ***Primeira Crise do Estreito de Taiwan***.")
        st.image("taiwan.jpg" , caption="A Ilha Formosa (Taiwan)")
        st.subheader("1967:")
        st.markdown("***Dagen H*** na *Suécia*: durante a noite, o tráfego muda de dirigir à esquerda para circular à direita.")
        st.image("autocarro.jpg")
        st.subheader("1971:")
        st.markdown("O ***Catar*** torna-se um estado independente.")
        st.image("catar.jpg" , caption="A bandeira catari")
        st.subheader("1976:")
        st.markdown("Integrando o programa *Viking*, a nave espacial ***Viking 2*** aterra na *Utopia Planitia*, em ***Marte***.")
        st.image("viking2.jpg" , caption="A nave espacial Viking 2")
        st.subheader("1981:")
        st.markdown("Instítuida pelas *Nações Unidas*, a ***Convenção sobre a eliminação de todas as formas de descriminação contra as mulheres***, uma declaração internacional de direitos das mulheres, entra em vigor.")
        st.image("nacoesunidas.jpg" , caption="Sala da Assembleia Geral da Organização das Nações Unidas, em Nova York")
        st.subheader("1987:")
        st.markdown("Durante um *Golpe de Estado*, o Presidente do *Burundi* ***Jean-Batptiste Bagaza*** é deposto pelo *major* ***Pierre Buyoya***.")
        st.image("bagaza.jpg" , caption="O Presidente deposto Jean-Baptiste Bagaza")
        st.subheader("1989:")
        st.markdown("O voo *Varig 254* faz uma aterragem de emrgência sobre uma região localizada a cerca de 60 Km a norte de *São José do Xingu, Mato Grosso, em consequência de falta de combustível; ***12 passageiros morreram.")
        st.image("varig.jpg" , caption="O avião envolvido no acidente, estacionado no Aeroporto Internacional do Rio de Janeiro-Galeão em outubro de 1983")
        st.subheader("1994:")
        st.markdown("Durante a ***Rutura sino-soviética***, a *Federação Russa* e a *Républica Popular da China* concordam em desalinhar as suas ***armas nucleares*** umas contra as outras.")
        st.image("mao.jpg" , caption="Mao e Stalin")
        st.subheader("1995:")
        st.markdown("O ***Ebay*** é fundado, nos *Estados Unidos+.")
        st.image("ebay.jpg" , caption="Logotipo do Ebay")
    if SeculoXXI and condition == True:
        st.subheader("2004:")
        st.markdown("Termina o ***cerco à escola de Beslan***, na *República Russa da Ossétia do Norte*, com, pelo menos, ***334 mortos***, a maioria crianças.")
        st.image("beslan.jpg" , caption="A escola do massacre de Beslan")
        st.subheader("2016:")
        st.markdown("Os ***EUA*** e a ***China***, juntos responsáveis por *40%* das emissões mundiais de carbono, ratificam formalmente o ***Acordo Climático Global de Paris***.")
        st.image("acordo.jpg")
        st.subheader("2017:")
        st.markdown("A *Coreia do Norte* conduz o seu sexto, e mais poderoso, ***teste nuclear***.")
        st.image("coreia.jpg" , caption="Teste nuclear efetuado pela Coreia do Norte em 2022")
#Nascimentos:
