#Importar algumas bibliotecas
import streamlit as st

#*********************************Início da APP***********************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************
#Título:
st.title("Um dia na História")

#Saudação inicial
st.write("Bem vinda, Maria!")

#Estabelecer o dia:
st.header("3 de setembro")
st.write("O dia 3 de setembro é uma data histórica: foi no 246º dia do calendário gregoriano (247º em anos bissextos) que se deram vários acontecimentos históricos de grande relevo.")

#Caso o utilizador não selecione nenhum tipo de acontecimento esta secção irá encorajá-lo:
st.markdown('De facto, o dia 3 de setembro é um um dia - desculpa pelo pleonasmo - *histórico*. Algumas pessoas **nasceram**, outras **morreram**; deram-se **eventos**... . Se te apetecer, Maria, estás à vontade para descobrir o que aconteceu ao certo ao longo da história nesta data (para isso, podes utilizar a "*side bar*"). Deixo-te um insentivo: aqui algures, nesta app, existe uma ***secção escondida***!')

#Estabelecer a categoria de acontecimentos
with st.sidebar:
    st.markdown("**Tipos de acontecimentos a visualizar:**")
    EventosHistóricos = st.toggle("Eventos Históricos")
    Nascimentos = st.toggle("Nascimentos")
    Mortes = st.toggle("Mortes")
    condition = True #Uma variável que permite interromper o código, para que não exista repetição de dados apresentados.

#Eliminar possíveis erros:
if (EventosHistóricos and Nascimentos) or (EventosHistóricos and Mortes) or (Nascimentos and Mortes):
    col1, col2, col3 = st.columns(3)
    col1.metric("" , "" , "")
    col2.metric("" , "Erro*" , "")
    col3.metric("" , "" , "")
    st.write("*Esta APP foi desenvolvida de forma a evidenciar apenas uma categoria de acontecimentos em simultaneo.")

#Eventos históricos:
elif EventosHistóricos:
        st.subheader("Principais Eventos Históricos" , divider= "rainbow")
        #Estabelecer que épocas evidenciar
        with st.sidebar:
            st.markdown("**Por favor selecione as principais épocas a visualizar:**")
            SeculosAntesDeCristo = st.toggle("Séculos antes de Cristo (a.C.)")              #a.C.
            SeculoIaXI = st.toggle("Século I a século XI")                                  #I a XI
            SeculoXIIaXIX = st.toggle("Século XII a seculo XIX")                            #XII a XIX
            SeculoXX = st.toggle("Século XX")                                               #XX
            SeculoXXI = st.toggle("Século XXI")                                             #XXI
            TodasAsEpocas = st.toggle("Todas as épocas")                                    #Todas
        if TodasAsEpocas:
            condition = False
            st.markdown("")
            st.subheader("36 a.C. :")
            st.markdown("Na *Batalha de Nauloco*, ***Marco Vipsânio Agripa***, almirante de ***Otávio***, derrota ***Sexto Pompeu***, filho de ***Pompeo***, terminando assim a resistência pompeana ao *Segundo Triunvirato*.")
            st.image("nauloco.jpg", caption="Batalha de Nauloco")
            st.subheader("301:")
            st.markdown("***San Marino***, um dos mais pequenos países do mundo, e a república mais antiga ainda existente, é fundada por *São Marino*.")
            st.image("sanmarino.jpg" , caption="Bandeira de San Marino")
            st.subheader("590:")
            st.markdown("O ***Papa Gregório I***, ou *São Gregório Magnum*, é eleito.")
            st.image("gregorio.jpg" , caption="Papa Gregório I")
            st.subheader("673:")
            st.markdown("O Rei ***Vamba*** dos *Visigodos* reprime uma revolta de ***Hilderico***, governador de *Nimes* e rival ao trono.")
            st.image("vamba.jpg" , caption="A coroação do Rei Vamba")
            st.subheader("863:")
            st.markdown("Maior vitória bizantina na ***Batlha de Lalacão*** contra uma ataque árabe.")
            st.image("lalacao.jpg" , caption="Batlha de Lalacão")
            st.subheader("1189:")
            st.markdown("Coroação de ***Ricardo I*** de *Inglaterra*.")
            st.image("ricardo.jpg" , caption="Coroação de Ricardo I de Inglaterra")
            st.subheader("1260:")
            st.markdown("Os *mamelucos* derrotam os *mongóis* na ***Batalha de Ain Jalut*** na *Palestina*, marcando a sua primeira derrota decisiva e o ponto de máxima expansão do *Império Mongol*.")
            st.image("ainjalut.jpg" , caption="Batalha de Ain Jalut")
            st.subheader("1335:")
            st.markdown("No *Congresso de Visegrád*, ***Carlos I da Hungria*** media uma reconciliação entre dois monarcas vizinhos, ***João da Boêmia*** e ***Casemiro III da Polónia***.")
            st.image("carlosI.jpg" , caption="Carlos I")
            st.subheader("1384:")
            st.markdown("Levamtamento do ***Cerco de Lisboa*** devido, sobretudo, à *Peste Negra*, que assolava o exército castelhano.")
            st.image("lisboa.jpg" , caption="Cerco a Lisboa de 1384")
            st.subheader("1411:")
            st.markdown("É celebrado o ***Tratado de Selymbria*** entre o *Império Otomano* e a *República de Veneza*.")
            st.image("selymbria.jpg" , caption="Tratado de Selymbria")
            st.subheader("1650:")
            st.markdown("A vitória sobre os monarquistas, na ***Batalha de Dunbar*** abre o caminho para *Edinburgh* para o **Novo Exército Modelo** na *Terceira Guerra Civil Inglesa*.")
            st.image("dunbar.jpg" , caption="Batlha de Dunbar")
            st.subheader("1658:")
            st.markdown("Aquando da morte de ***Oliver Cromwell***, o seu filho, ***Richard Cromwell***, torna-se o *Lorde Protetor* de Inglaterra.")
            st.image("cromwell.jpg" , caption="Richard Cromwell")
            st.subheader("1666:")
            st.markdown("O *Royal Exchange* arde, no ***Grande Incêndio de Londres***.")
            st.image("incendio.jpg" , caption="O Grande Incêndio de Londres")
            st.subheader("1758:")
            st.markdown("*D. José I* escapa de uma tentativa de rgicídio, da qual resulta o ***Processo dos Távoras***.")
            st.image("tavoras.jpg" , caption="Execução pública dos Távoras")
            st.subheader("1759:")
            st.markdown("Expulsão dos ***jesuítas*** dos terristórios portugueses.")
            st.image("jesuitas.jpg")
            st.subheader("1783:")
            st.markdown("A ***Guerra da Independência dos Estados Unidos*** termina com a assinatura do *Tratado de Paris* pelos Estados Unidos e o Reino da Grã-Bretanha.")
            st.image("teaparty.jpg" , caption="Tea Party: o início da revolução americana")
            st.subheader("1843:")
            st.markdown("O rei ***Otto, da Grécia*** é forçado a conceder uma nova constituição após uma *revolta* em Atenas")
            st.image("otto.jpg" , caption="O rei Otto")
            st.subheader("1861:")
            st.markdown("Durante a *Guerra Civil Americana* o general confederado ***Leonidas Polk*** invade o neutro ***Kentucky***, fazendo com que a *legislatura estadual* pedisse a ajuda da ***União***.")
            st.image("confederados.jpg" , caption="Bandeira dos Estados Confederados da América")
            st.subheader("1870:")
            st.markdown("Durante a *Guerra Franco-Prussiana*** começa o ***Cerco de Metz***, que, mais tarde, viria a resultar numa vitória prussiana decisiva.")
            st.image("metz.jpg" , caption="Um dos fortes de Metz sobre ocupação alemã, após a rendição francesa")
            st.subheader("1914:")
            st.markdown("O ***Cardeal Giacomo della Chiesa*** é eleito *papa* e adota o nome de ***Bento XV***.")
            st.image("bento.jpg" , caption="O papa Bento XV")
            st.markdown("***Guilherme***, ***Príncipe da Albânia***, deixa o país após apenas seis meses de *reinado*, devido à opsição face ao seu governo.")
            st.image("guilherme.jpg" , caption="Guilherme,Prícipe da Albânia.")
            st.markdown("Durante ***A Primeira Guerra Mundial***, tem início a ***Batalha de Grand Couronné***: um assalto alemão contra as posições francesas em terreno elevado perto da cidade de *Nancy*.")
            st.image("couronne.jpg" , caption="Mapa dos vetores da Batalha de Grand Couronné.")
            st.subheader("1939:")
            st.markdown("A ***Segunda Guerra Mundial*** tem início quando a *França*, *Reino Unido*, *Nova Zelândia* e *Austrália* declaram guerra à *Alemanha* após a invasão da *Polónia*, formando os ***Aliados***.")
            st.image("paris.jpg" , caption="Fotografia que retrata Breker, Speer e Hitler em Paris, numa excurção de sensivelmente três horas após a capitulação francesa, a 23 de junho de 1940.")
            st.subheader("1941:")
            st.markdown("*Karl Fritzsch*, vice-comandante do ***Campo de Concentração de Auschwitz***, experimenta o uso de ***Zyklon B*** no gaseamento de prisioneiros de guerra soviéticos.")
            st.image("auschwitz.jpg" , caption="O Campo de Concentração de Auschwitz")
            st.subheader("1943:")
            st.markdown("Durante a ***Segunda Guerra Mundial*** a invasão *Aliada* da *Itália* começa no mesmo dia em que o general americano *Dwight D. Eisenhower* e o marechal italiano *Pietro Badoglio* assinam o ***Armistício de Cassibile*** a bordo do couroçado da *Royal Navy HMS Nelson*")
            st.image("nelson.jpg" , caption="His Majesty's Ship (HMS) Nelson")
            st.subheader("1944:")
            st.markdown("***Anne Frank*** e a família são enviados no último comboio de transporte entre o ***Campo de Westerbork*** e o ***Campo de Concentração de Auschwitz***, chegando três dias depois.")
            st.image("annefrank.jpg" , caption="Anne Frank")
            st.subheader("1945:")
            st.markdown("Começa uma celebração de três dias na *China*, após o ***Dia da Vitória sobre o Japão***.")
            st.image("japao.jpg" , caption="Representantes japoneses chegam ao USS Missouri de forma a oficializar a rendição do seu país")
            st.subheader("1950:")
            st.markdown("*Nino* Farina torna-se o primeiro campeão de ***Formula 1*** depois de vencer o ***Grande Prémio de Itália***.")
            st.image("farina.jpg" , caption="Nino Farina no seu Formula")
            st.subheader("1954:")
            st.markdown("O ***Exército da Libertação Popular*** começa a bombardear as ilhas *Kinmen*, controladas pela *Républica da China*, dando início à ***Primeira Crise do Estreito de Taiwan***.")
            st.image("taiwan.jpg" , caption="A Ilha Formosa (Taiwan)")
            st.subheader("1967:")
            st.markdown("***Dagen H*** na *Suécia*: durante a noite, o tráfego muda de dirigir à esquerda para circular à direita.")
            st.image("autocarro.jpg")
            st.subheader("1971:")
            st.markdown("O ***Catar*** torna-se um estado independente.")
            st.image("catar.jpg" , caption="A bandeira catari")
            st.subheader("1976:")
            st.markdown("Integrando o programa *Viking*, a nave espacial ***Viking 2*** aterra na *Utopia Planitia*, em ***Marte***.")
            st.image("viking2.jpg" , caption="A nave espacial Viking 2")
            st.subheader("1981:")
            st.markdown("Instítuida pelas *Nações Unidas*, a ***Convenção sobre a eliminação de todas as formas de descriminação contra as mulheres***, uma declaração internacional de direitos das mulheres, entra em vigor.")
            st.image("nacoesunidas.jpg" , caption="Sala da Assembleia Geral da Organização das Nações Unidas, em Nova York")
            st.subheader("1987:")
            st.markdown("Durante um *Golpe de Estado*, o Presidente do *Burundi* ***Jean-Batptiste Bagaza*** é deposto pelo *major* ***Pierre Buyoya***.")
            st.image("bagaza.jpg" , caption="O Presidente deposto Jean-Baptiste Bagaza")
            st.subheader("1989:")
            st.markdown("O voo *Varig 254* faz uma aterragem de emergência sobre uma região localizada a cerca de 60 Km a norte de *São José do Xingu*, Mato Grosso, em consequência de falta de combustível; ***12 passageiros morreram***.")
            st.image("varig.jpg" , caption="O avião envolvido no acidente, estacionado no Aeroporto Internacional do Rio de Janeiro-Galeão em outubro de 1983")
            st.subheader("1994:")
            st.markdown("Durante a ***Rutura sino-soviética***, a *Federação Russa* e a *Républica Popular da China* concordam em desalinhar as suas ***armas nucleares*** umas contra as outras.")
            st.image("mao.jpg" , caption="Mao e Stalin")
            st.subheader("1995:")
            st.markdown("O ***Ebay*** é fundado, nos *Estados Unidos*.")
            st.image("ebay.jpg" , caption="Logotipo do Ebay")
            st.subheader("2004:")
            st.markdown("Termina o ***cerco à escola de Beslan***, na *República Russa da Ossétia do Norte*, com, pelo menos, ***334 mortos***, a maioria crianças.")
            st.image("beslan.jpg" , caption="A escola do massacre de Beslan")
            st.subheader("2016:")
            st.markdown("Os ***EUA*** e a ***China***, juntos responsáveis por *40%* das emissões mundiais de carbono, ratificam formalmente o ***Acordo Climático Global de Paris***.")
            st.image("acordo.jpg")
            st.subheader("2017:")
            st.markdown("A *Coreia do Norte* conduz o seu sexto, e mais poderoso, ***teste nuclear***.")
            st.image("coreia.jpg" , caption="Teste nuclear efetuado pela Coreia do Norte em 2022")
        if SeculosAntesDeCristo and condition == True:
            st.markdown("")
            st.subheader("36 a.C. :")
            st.markdown("Na *Batalha de Nauloco*, ***Marco Vipsânio Agripa***, almirante de ***Otávio***, derrota ***Sexto Pompeu***, filho de ***Pompeo***, terminando assim a resistência pompeana ao *Segundo Triunvirato*.")
            st.image("nauloco.jpg", caption="Batalha de Nauloco")
        if SeculoIaXI and condition == True:
            st.subheader("301:")
            st.markdown("***San Marino***, um dos mais pequenos países do mundo, e a república mais antiga ainda existente, é fundada por *São Marino*.")
            st.image("sanmarino.jpg" , caption="Bandeira de San Marino")
            st.subheader("590:")
            st.markdown("O ***Papa Gregório I***, ou *São Gregório Magnum*, é eleito.")
            st.image("gregorio.jpg" , caption="Papa Gregório I")
            st.subheader("673:")
            st.markdown("O Rei ***Vamba*** dos *Visigodos* reprime uma revolta de ***Hilderico***, governador de *Nimes* e rival ao trono.")
            st.image("vamba.jpg" , caption="A coroação do Rei Vamba")
            st.subheader("863:")
            st.markdown("Maior vitória bizantina na ***Batlha de Lalacão*** contra uma ataque árabe.")
            st.image("lalacao.jpg" , caption="Batlha de Lalacão")
        if SeculoXIIaXIX and condition == True:
            st.subheader("1189:")
            st.markdown("Coroação de ***Ricardo I*** de *Inglaterra*.")
            st.image("ricardo.jpg" , caption="Coroação de Ricardo I de Inglaterra")
            st.subheader("1260:")
            st.markdown("Os *mamelucos* derrotam os *mongóis* na ***Batalha de Ain Jalut*** na *Palestina*, marcando a sua primeira derrota decisiva e o ponto de máxima expansão do *Império Mongol*.")
            st.image("ainjalut.jpg" , caption="Batalha de Ain Jalut")
            st.subheader("1335:")
            st.markdown("No *Congresso de Visegrád*, ***Carlos I da Hungria*** media uma reconciliação entre dois monarcas vizinhos, ***João da Boêmia*** e ***Casemiro III da Polónia***.")
            st.image("carlosI.jpg" , caption="Carlos I")
            st.subheader("1384:")
            st.markdown("Levamtamento do ***Cerco de Lisboa*** devido, sobretudo, à *Peste Negra*, que assolava o exército castelhano.")
            st.image("lisboa.jpg" , caption="Cerco a Lisboa de 1384")
            st.subheader("1411:")
            st.markdown("É celebrado o ***Tratado de Selymbria*** entre o *Império Otomano* e a *República de Veneza*.")
            st.image("selymbria.jpg" , caption="Tratado de Selymbria")
            st.subheader("1650:")
            st.markdown("A vitória sobre os monarquistas, na ***Batalha de Dunbar*** abre o caminho para *Edinburgh* para o **Novo Exército Modelo** na *Terceira Guerra Civil Inglesa*.")
            st.image("dunbar.jpg" , caption="Batlha de Dunbar")
            st.subheader("1658:")
            st.markdown("Aquando da morte de ***Oliver Cromwell***, o seu filho, ***Richard Cromwell***, torna-se o *Lorde Protetor* de Inglaterra.")
            st.image("cromwell.jpg" , caption="Richard Cromwell")
            st.subheader("1666:")
            st.markdown("O *Royal Exchange* arde, no ***Grande Incêndio de Londres***.")
            st.image("incendio.jpg" , caption="O Grande Incêndio de Londres")
            st.subheader("1758:")
            st.markdown("*D. José I* escapa de uma tentativa de rgicídio, da qual resulta o ***Processo dos Távoras***.")
            st.image("tavoras.jpg" , caption="Execução pública dos Távoras")
            st.subheader("1759:")
            st.markdown("Expulsão dos ***jesuítas*** dos terristórios portugueses.")
            st.image("jesuitas.jpg")
            st.subheader("1783:")
            st.markdown("A ***Guerra da Independência dos Estados Unidos*** termina com a assinatura do *Tratado de Paris* pelos Estados Unidos e o Reino da Grã-Bretanha.")
            st.image("teaparty.jpg" , caption="Tea Party: o início da revolução americana")
            st.subheader("1843:")
            st.markdown("O rei ***Otto, da Grécia*** é forçado a conceder uma nova constituição após uma *revolta* em Atenas")
            st.image("otto.jpg" , caption="O rei Otto")
            st.subheader("1861:")
            st.markdown("Durante a *Guerra Civil Americana* o general confederado ***Leonidas Polk*** invade o neutro ***Kentucky***, fazendo com que a *legislatura estadual* pedisse a ajuda da ***União***.")
            st.image("confederados.jpg" , caption="Bandeira dos Estados Confederados da América")
            st.subheader("1870:")
            st.markdown("Durante a *Guerra Franco-Prussiana*** começa o ***Cerco de Metz***, que, mais tarde, viria a resultar numa vitória prussiana decisiva.")
            st.image("metz.jpg" , caption="Um dos fortes de Metz sobre ocupação alemã, após a rendição francesa")
        if SeculoXX and condition == True:
            st.subheader("1914:")
            st.markdown("O ***Cardeal Giacomo della Chiesa*** é eleito *papa* e adota o nome de ***Bento XV***.")
            st.image("bento.jpg" , caption="O papa Bento XV")
            st.markdown("***Guilherme***, ***Príncipe da Albânia***, deixa o país após apenas seis meses de *reinado*, devido à opsição face ao seu governo.")
            st.image("guilherme.jpg" , caption="Guilherme,Prícipe da Albânia.")
            st.markdown("Durante ***A Primeira Guerra Mundial***, tem início a ***Batalha de Grand Couronné***: um assalto alemão contra as posições francesas em terreno elevado perto da cidade de *Nancy*.")
            st.image("couronne.jpg" , caption="Mapa dos vetores da Batalha de Grand Couronné.")
            st.subheader("1939:")
            st.markdown("A ***Segunda Guerra Mundial*** tem início quando a *França*, *Reino Unido*, *Nova Zelândia* e *Austrália* declaram guerra à *Alemanha* após a invasão da *Polónia*, formando os ***Aliados***.")
            st.image("paris.jpg" , caption="Fotografia que retrata Breker, Speer e Hitler em Paris, numa excurção de sensivelmente três horas após a capitulação francesa, a 23 de junho de 1940.")
            st.subheader("1941:")
            st.markdown("*Karl Fritzsch*, vice-comandante do ***Campo de Concentração de Auschwitz***, experimenta o uso de ***Zyklon B*** no gaseamento de prisioneiros de guerra soviéticos.")
            st.image("auschwitz.jpg" , caption="O Campo de Concentração de Auschwitz")
            st.subheader("1943:")
            st.markdown("Durante a ***Segunda Guerra Mundial*** a invasão *Aliada* da *Itália* começa no mesmo dia em que o general americano *Dwight D. Eisenhower* e o marechal italiano *Pietro Badoglio* assinam o ***Armistício de Cassibile*** a bordo do couroçado da *Royal Navy HMS Nelson*")
            st.image("nelson.jpg" , caption="His Majesty's Ship (HMS) Nelson")
            st.subheader("1944:")
            st.markdown("***Anne Frank*** e a família são enviados no último comboio de transporte entre o ***Campo de Westerbork*** e o ***Campo de Concentração de Auschwitz***, chegando três dias depois.")
            st.image("annefrank.jpg" , caption="Anne Frank")
            st.subheader("1945:")
            st.markdown("Começa uma celebração de três dias na *China*, após o ***Dia da Vitória sobre o Japão***.")
            st.image("japao.jpg" , caption="Representantes japoneses chegam ao USS Missouri de forma a oficializar a rendição do seu país")
            st.subheader("1950:")
            st.markdown("*Nino* Farina torna-se o primeiro campeão de ***Formula 1*** depois de vencer o ***Grande Prémio de Itália***.")
            st.image("farina.jpg" , caption="Nino Farina no seu Formula")
            st.subheader("1954:")
            st.markdown("O ***Exército da Libertação Popular*** começa a bombardear as ilhas *Kinmen*, controladas pela *Républica da China*, dando início à ***Primeira Crise do Estreito de Taiwan***.")
            st.image("taiwan.jpg" , caption="A Ilha Formosa (Taiwan)")
            st.subheader("1967:")
            st.markdown("***Dagen H*** na *Suécia*: durante a noite, o tráfego muda de dirigir à esquerda para circular à direita.")
            st.image("autocarro.jpg")
            st.subheader("1971:")
            st.markdown("O ***Catar*** torna-se um estado independente.")
            st.image("catar.jpg" , caption="A bandeira catari")
            st.subheader("1976:")
            st.markdown("Integrando o programa *Viking*, a nave espacial ***Viking 2*** aterra na *Utopia Planitia*, em ***Marte***.")
            st.image("viking2.jpg" , caption="A nave espacial Viking 2")
            st.subheader("1981:")
            st.markdown("Instítuida pelas *Nações Unidas*, a ***Convenção sobre a eliminação de todas as formas de descriminação contra as mulheres***, uma declaração internacional de direitos das mulheres, entra em vigor.")
            st.image("nacoesunidas.jpg" , caption="Sala da Assembleia Geral da Organização das Nações Unidas, em Nova York")
            st.subheader("1987:")
            st.markdown("Durante um *Golpe de Estado*, o Presidente do *Burundi* ***Jean-Batptiste Bagaza*** é deposto pelo *major* ***Pierre Buyoya***.")
            st.image("bagaza.jpg" , caption="O Presidente deposto Jean-Baptiste Bagaza")
            st.subheader("1989:")
            st.markdown("O voo *Varig 254* faz uma aterragem de emergência sobre uma região localizada a cerca de 60 Km a norte de *São José do Xingu*, Mato Grosso, em consequência de falta de combustível; ***12 passageiros morreram***.")
            st.image("varig.jpg" , caption="O avião envolvido no acidente, estacionado no Aeroporto Internacional do Rio de Janeiro-Galeão em outubro de 1983")
            st.subheader("1994:")
            st.markdown("Durante a ***Rutura sino-soviética***, a *Federação Russa* e a *Républica Popular da China* concordam em desalinhar as suas ***armas nucleares*** umas contra as outras.")
            st.image("mao.jpg" , caption="Mao e Stalin")
            st.subheader("1995:")
            st.markdown("O ***Ebay*** é fundado, nos *Estados Unidos*.")
            st.image("ebay.jpg" , caption="Logotipo do Ebay")
        if SeculoXXI and condition == True:
            st.subheader("2004:")
            st.markdown("Termina o ***cerco à escola de Beslan***, na *República Russa da Ossétia do Norte*, com, pelo menos, ***334 mortos***, a maioria crianças.")
            st.image("beslan.jpg" , caption="A escola do massacre de Beslan")
            st.subheader("2016:")
            st.markdown("Os ***EUA*** e a ***China***, juntos responsáveis por *40%* das emissões mundiais de carbono, ratificam formalmente o ***Acordo Climático Global de Paris***.")
            st.image("acordo.jpg")
            st.subheader("2017:")
            st.markdown("A *Coreia do Norte* conduz o seu sexto, e mais poderoso, ***teste nuclear***.")
            st.image("coreia.jpg" , caption="Teste nuclear efetuado pela Coreia do Norte em 2022")    

#Nascimentos:
elif Nascimentos:
        st.subheader("Pricipais Nascimentos" , divider= "rainbow")
        #Estabelecer épocas a evidenciar
        with st.sidebar:
            st.markdown("**Por favor selecione as principais épocas a visualizar:**")
            AteSeculoXIX = st.toggle("Anteriores ao século XIX")
            SeculoXIX = st.toggle("Século XIX")
            SeculoXX = st.toggle("Século XX")
            if SeculoXX:
                PrimeiraMetade = st.checkbox("1901-1950")
                SegundaMetade = st.checkbox("1951-2000")
            SeculoXXI = st.toggle("Século XXI")
            TodasAsEpocas = st.toggle("Todas as épocas")
        if TodasAsEpocas:
            condition = False
            st.subheader("1499:")
            st.markdown("Nasce ***Diane de Poitiers***, a preferida de *Henrique II*, de *França*. (m. 1566)")
            st.image("diane.jpg")
            st.subheader("1668:")
            st.markdown("Nasce ***Isabel de Meckemburgo-Güstrow***, Duquesa de *Saxe-Merseburgo*. (m. 1738)")
            st.image("isabel.jpg")
            st.subheader("1704:")
            st.markdown("Nasce ***Joseph de Jussieu***, explorador, geógrafo e matemático *francês*. (m. 1779)")
            st.image("jussieu.jpg")
            st.subheader("1710:")
            st.markdown("Nasce ***Abraham Trembley***, biólogo e zoólogo *suíço*. (m. 1784)")
            st.image("trembley.jpg")
            st.subheader("1741:")
            st.markdown("Nasce ***Johann Wilhelm von Archenholz***, oficial, escritor e editor prussiano. (m. 1812)")
            st.image("archenholz.jpg")
            st.subheader("1781:")
            st.markdown("Nasce ***Eugène de Beauharnais***, príncipe do *Império Francês*, militar, vice-rei de *Itália* e Duque de *Leuchtenberg*. (m. 1824)")
            st.image("eugene.jpg")
            st.subheader("1787:")
            st.markdown("Nasce ***Eléonore Denuelle de la Plaigne***, cortesã francesa. (m.1868)")
            st.image("eleanore.jpg")
            st.subheader("1790:")
            st.markdown("Nasce ***Francisco Acuña de Figueroa***, poeta uruguaio. (m.1862)")
            st.image("figueroa.jpg")
            st.subheader("1810:")
            st.markdown("Nasce ***Paul Kane***, pintor irlando-canadense. (m.1871)")
            st.image("kane.jpg" , caption="Auto-retrato, 1845")
            st.subheader("1814:")
            st.markdown("Nasce ***James Joseph Sylvester***, matemático e académico britânico. (m. 1897)")
            st.image("sylvester.jpg")
            st.subheader("1869:")
            st.markdown("Nasce ***Fritz Pregl***, químico austríaco. (m. 1930)")
            st.image("pregl.jpg")
            st.subheader("1875:")
            st.markdown("Nasce ***Ferdinand Porsche***, empresário austríaco e fundador da Porsche. (m. 1951)")
            st.image("porsche.jpg")
            st.subheader("1881:")
            st.markdown("Nasce ***Margherita Ancona***, professora e sufragista italiana. (m.1966)")
            st.image("margherita.jpg" , caption="Conferência Interaliada das Mulheres")
            st.subheader("1883:")
            st.markdown("Nasce ***António Sérgio***, pensador português. (m. 1969)")
            st.image("AntonioSergio.jpg")
            st.subheader("1888:")
            st.markdown("Nasce ***Nereu Ramos***, advogado e político brasileiro, *20º Presidente do Brasil*. (m. 1958)")
            st.image("nereu.jpg")
            st.subheader("1894:")
            st.markdown("Nasce ***André Hébuterne***, pintor francês. (m.1992)")
            st.image("hebuterne.jpg" , caption="Le marché à Meaux: André Hébuterne")
            st.subheader("1897:")
            st.markdown("Nasce ***Francisco Mignone***, maestro e compositor brasileiro. (m. 1986)")
            st.image("mignone.jpg")
            st.subheader("1900:")
            st.markdown("Nasce ***Urho Kekkonen***, jornalista, advogado e político finlandês, *8º Presidente da Finlândia*. (m. 1986)")
            st.image("urho.jpg")
            st.subheader("1905:")
            st.markdown("Nasce ***Carl David Anderson***, físico estadunidense. (m. 1991)")
            st.image("anderson.jpg" , caption="Pintura por Tim Tompkins")
            st.subheader("1907:")
            st.markdown("Nasce ***Loren Eiseley***, antropólogo, filósofo e autor americano. (m. 1977)")
            st.image("eiseley.jpg")
            st.subheader("1908:")
            st.markdown("Nasce ***Lev Pontryagin***, matemático e académico russo. (m. 1988)")
            st.image("lev.jpg")
            st.subheader("1922:")
            st.markdown("Nasce ***Burt Kennedy***, roteirista e cineasta estadunidense. (m. 2001)")
            st.image("kennedy.jpg")
            st.subheader("1923:")
            st.markdown("Nasce ***Mort Walker***, cartunista estadunidense. (m. 2018)")
            st.image("walker.jpg")
            st.markdown("Nasce ***Glenn Bell***, fundador da *Taco Bell*. (m. 2010)")
            st.image("bell.jpg")
            st.subheader("1926:")
            st.markdown("Nasce ***Irene Pappás***, atriz e cantora grega. (m. 2022)")
            st.image("pappas.jpg")
            st.subheader("1931:")
            st.markdown("Nasce ***Paulo Maluf***, político brasileiro.")
            st.image("maluf.jpg")
            st.markdown("Nasce ***Michael Fischer***, físico e químico britanico. (m. 2021)")
            st.image("fischer.jpg")
            st.subheader("1932:")
            st.markdown("Nasce ***José Manuel Ferreira Simões***, jornalista português. (m. 2014)")
            st.image("simoes.jpg")
            st.subheader("1938:")
            st.markdown("Nasce ***Ryoji Noyori***, químico japonês.")
            st.image("noyori.jpg")
            st.subheader("1940:")
            st.markdown("Nasce ***Eduardo Galeano***, jornalista e escritor uruguaio. (m. 2015)")
            st.image("galeano.jpg")
            st.subheader("1942:")
            st.markdown("Nasce ***Alan Jardine***, músico americano.")
            st.image("jardine.jpg")
            st.subheader("1943:")
            st.markdown("Nasce ***Mário Juruna***, líder indígena e político brasileiro. (m. 2002)")
            st.image("juruna.jpg")
            st.subheader("1946:")
            st.markdown("Nasce ***Dirceu Lopes***, futebolista brasileiro.")
            st.image("dirceu.jpg")
            st.subheader("1949:")
            st.markdown("Nasce ***José Pékerman***, treinador argentino de futebol.")
            st.image("pekerman.jpg")
            st.subheader("1955:")
            st.markdown("Nasce ***Serginho Leite***, músico, humorista e locutor brasileiro. (m. 2011)")
            st.image("leite.jpg")
            st.subheader("1960:")
            st.markdown("Nasce ***Perry Bamonte***, músico britanico.")
            st.image("bamonte.jpg")
            st.subheader("1963:")
            st.markdown("Nasce ***Amber Lynn***, atriz *pornográfica* estadunidense.")
            st.image("lynn.jpg")
            st.subheader("1964:")
            st.markdown("Nasce ***Adam Curry***, empresário estadunidense.")
            st.image("curry.jpg")
            st.markdown("Nasce ***Gisele Froés***, atriz brasileira.")
            st.image("froes.jpg")
            st.subheader("1965:")
            st.markdown("Nasce ***Charlie Sheen***, ator estadunidense.")
            st.image("sheen.jpg")
            st.markdown("Nasce ***Carlos Eugênio Simon***, árbitro de futebol brasileiro.")
            st.image("simon.jpg")
            st.subheader("1969:")
            st.markdown("Nasce ***Jörg Müller***, piloto de automóveis alemão.")
            st.image("muller.jpg")
            st.subheader("1970:")
            st.markdown("Nasce ***Gareth Southgate***, futebolista e treinador britanico de futebol.")
            st.image("southgate.jpg")
            st.subheader("1971:")
            st.markdown("Nasce ***Luciano Huck***, apresentador de televisão brasileiro.")
            st.image("huck.jpg")
            st.markdown("Nasce ***Paolo Montero***, futebolista uruguaio.")
            st.image("montero.jpg")
            st.markdown("Nasce ***Emerson Ferretti***, futebolista brasilero.")
            st.image("ferretti.jpg")
            st.subheader("1973:")
            st.markdown("Nasce ***Jennifer Paige***, cantora estadunidense.")
            st.image("paige.jpg")
            st.subheader("1974:")
            st.markdown("Nasce ***Didier André***, piloto de automóveis francês.")
            st.image("didier.jpg" , caption="Didier André no seu Gran Turismo")
            st.subheader("1979:")
            st.markdown("Nasce ***Júlio César***, futebolista brasileiro.")
            st.image("julio.jpg")
            st.markdown("Nasce ***Tomo Miličević***, guitarrista croata.")
            st.image("tomo.jpg")
            st.subheader("1980:")
            st.markdown("Nasce ***Daniel Bilos***, futebolista argentino.")
            st.image("bilos.jpg")
            st.markdown("Nasce ***Lauro***, futebolista brasileiro.")
            st.image("lauro.jpg")
            st.subheader("1982:")
            st.markdown("Nasce ***Leo Lins***, humorista brasileiro.")
            st.image("lins.jpg")
            st.markdown("Nasce ***Thammy Miranda***, ator, repórter e político brasileiro.")
            st.image("thammy.jpg")
            st.subheader("1983:")
            st.markdown("Nasce ***Augusto Farfus***, piloto de automóveis brasileiro.")
            st.image("farfus.jpg")
            st.subheader("1984:")
            st.markdown("Nasce ***Garrett Hedlund***, ator estadunidense.")
            st.image("hedlund.jpg")
            st.subheader("1985:")
            st.markdown("Nasce ***Scott Carson***, futebolista britanico.")
            st.image("carson.jpg")
            st.markdown("Nasce ***Leandro Carrijo***, futebolista brasileiro.")
            st.image("carrijo.jpg")
            st.subheader("1986:")
            st.markdown("Nasce ***Leandro Franco da Rocha***, músico brasileiro.")
            st.image("franco.jpg")
            st.subheader("1988:")
            st.markdown("Nasce ***Carla Suárez Navarro***, tenista espanhola.")
            st.image("navarro.jpg")
            st.subheader("1989:")
            st.markdown("Nasce ***Bianca Bin***, atriz brasileira.")
            st.image("bin.jpg")
            st.markdown("Nasce ***Iza***, cantora e compositora brasileira.")
            st.image("iza.jpg")
            st.markdown("Nasce ***Rita Volk***, atriz estadunidense.")
            st.image("volk.jpg")
            st.subheader("1991:")
            st.markdown("Nasce ***Maurício Destri***, ator brasileiro.")
            st.image("destri.jpg")
            st.subheader("1993:")
            st.markdown("Nasce ***Lee Sung-jong***, cantor sul-coreano.")
            st.image("jong.jpg")
            st.markdown("Nasce ***Lee So-jung***, cantora sul-coreana.")
            st.image("jung.jpg")
            st.subheader("1996:")
            st.markdown("Nasce ***Joy***, cantora sul-coreana.")
            st.image("joy.jpg")
            st.subheader("1997:")
            st.markdown("Nasce ***Victor Meyniel***, ator, humorista e ex-youtuber brasileiro.")
            st.image("meyniel.jpg")
            st.subheader("1998:")
            st.markdown("Nasce ***Kanaphan Puitrakul***, ator, modelo e apresentador tailandês.")
            st.image("puitrakul.jpg")
            st.subheader("1999:")
            st.markdown("Nasce ***Rich Brian***, rapper chinês.")
            st.image("rich.jpg")
            st.subheader("2001:")
            st.markdown("Nasce ***Kata Blanka Vas***, desportista húngara.")
            st.image("blanka.jpg")
            st.subheader("2007:")
            st.markdown("Nasce ***Maria Coelho Santos***, estudante portuguesa.")
            st.image("maria.jpg")
            AcessoAreaSecreta = st.popover("Aceder à Área Secreta")
            with AcessoAreaSecreta:
               animal = st.text_input("Qual é o teu animal de estimação preferido?")
               animal_lower = animal.lower()
            if animal_lower in ["gato", "gatos", "gata", "gatas"]:
              col1, col2,  col3 = st.columns(3)
              col1.metric("" , "" , "")
              col2.metric("" , 'Parabéns!' , "")
              col3.metric("" , "" , "")
              st.balloons()
              st.balloons()
              st.balloons()
              st.balloons()
        if AteSeculoXIX and condition == True:
            st.subheader("1499:")
            st.markdown("Nasce ***Diane de Poitiers***, a preferida de *Henrique II*, de *França*. (m. 1566)")
            st.image("diane.jpg")
            st.subheader("1668:")
            st.markdown("Nasce ***Isabel de Meckemburgo-Güstrow***, Duquesa de *Saxe-Merseburgo*. (m. 1738)")
            st.image("isabel.jpg")
            st.subheader("1704:")
            st.markdown("Nasce ***Joseph de Jussieu***, explorador, geógrafo e matemático *francês*. (m. 1779)")
            st.image("jussieu.jpg")
            st.subheader("1710:")
            st.markdown("Nasce ***Abraham Trembley***, biólogo e zoólogo *suíço*. (m. 1784)")
            st.image("trembley.jpg")
            st.subheader("1741:")
            st.markdown("Nasce ***Johann Wilhelm von Archenholz***, oficial, escritor e editor prussiano. (m. 1812)")
            st.image("archenholz.jpg")
            st.subheader("1781:")
            st.markdown("Nasce ***Eugène de Beauharnais***, príncipe do *Império Francês*, militar, vice-rei de *Itália* e Duque de *Leuchtenberg*. (m. 1824)")
            st.image("eugene.jpg")
            st.subheader("1787:")
            st.markdown("Nasce ***Eléonore Denuelle de la Plaigne***, cortesã francesa. (m.1868)")
            st.image("eleanore.jpg")
            st.subheader("1790:")
            st.markdown("Nasce ***Francisco Acuña de Figueroa***, poeta uruguaio. (m.1862)")
            st.image("figueroa.jpg")
        if SeculoXIX and condition == True:
            st.subheader("1810:")
            st.markdown("Nasce ***Paul Kane***, pintor irlando-canadense. (m.1871)")
            st.image("kane.jpg" , caption="Auto-retrato, 1845")
            st.subheader("1814:")
            st.markdown("Nasce ***James Joseph Sylvester***, matemático e académico britânico. (m. 1897)")
            st.image("sylvester.jpg")
            st.subheader("1869:")
            st.markdown("Nasce ***Fritz Pregl***, químico austríaco. (m. 1930)")
            st.image("pregl.jpg")
            st.subheader("1875:")
            st.markdown("Nasce ***Ferdinand Porsche***, empresário austríaco e fundador da Porsche. (m. 1951)")
            st.image("porsche.jpg")
            st.subheader("1881:")
            st.markdown("Nasce ***Margherita Ancona***, professora e sufragista italiana. (m.1966)")
            st.image("margherita.jpg" , caption="Conferência Interaliada das Mulheres")
            st.subheader("1883:")
            st.markdown("Nasce ***António Sérgio***, pensador português. (m. 1969)")
            st.image("AntonioSergio.jpg")
            st.subheader("1888:")
            st.markdown("Nasce ***Nereu Ramos***, advogado e político brasileiro, *20º Presidente do Brasil*. (m. 1958)")
            st.image("nereu.jpg")
            st.subheader("1894:")
            st.markdown("Nasce ***André Hébuterne***, pintor francês. (m.1992)")
            st.image("hebuterne.jpg" , caption="Le marché à Meaux: André Hébuterne")
            st.subheader("1897:")
            st.markdown("Nasce ***Francisco Mignone***, maestro e compositor brasileiro. (m. 1986)")
            st.image("mignone.jpg")
            st.subheader("1900:")
            st.markdown("Nasce ***Urho Kekkonen***, jornalista, advogado e político finlandês, *8º Presidente da Finlândia*. (m. 1986)")
            st.image("urho.jpg")
        if SeculoXX and condition == True:
            if PrimeiraMetade:
                st.subheader("1905:")
                st.markdown("Nasce ***Carl David Anderson***, físico estadunidense. (m. 1991)")
                st.image("anderson.jpg" , caption="Pintura por Tim Tompkins")
                st.subheader("1907:")
                st.markdown("Nasce ***Loren Eiseley***, antropólogo, filósofo e autor americano. (m. 1977)")
                st.image("eiseley.jpg")
                st.subheader("1908:")
                st.markdown("Nasce ***Lev Pontryagin***, matemático e académico russo. (m. 1988)")
                st.image("lev.jpg")
                st.subheader("1922:")
                st.markdown("Nasce ***Burt Kennedy***, roteirista e cineasta estadunidense. (m. 2001)")
                st.image("kennedy.jpg")
                st.subheader("1923:")
                st.markdown("Nasce ***Mort Walker***, cartunista estadunidense. (m. 2018)")
                st.image("walker.jpg")
                st.markdown("Nasce ***Glenn Bell***, fundador da *Taco Bell*. (m. 2010)")
                st.image("bell.jpg")
                st.subheader("1926:")
                st.markdown("Nasce ***Irene Pappás***, atriz e cantora grega. (m. 2022)")
                st.image("pappas.jpg")
                st.subheader("1931:")
                st.markdown("Nasce ***Paulo Maluf***, político brasileiro.")
                st.image("maluf.jpg")
                st.markdown("Nasce ***Michael Fischer***, físico e químico britanico. (m. 2021)")
                st.image("fischer.jpg")
                st.subheader("1932:")
                st.markdown("Nasce ***José Manuel Ferreira Simões***, jornalista português. (m. 2014)")
                st.image("simoes.jpg")
                st.subheader("1938:")
                st.markdown("Nasce ***Ryoji Noyori***, químico japonês.")
                st.image("noyori.jpg")
                st.subheader("1940:")
                st.markdown("Nasce ***Eduardo Galeano***, jornalista e escritor uruguaio. (m. 2015)")
                st.image("galeano.jpg")
                st.subheader("1942:")
                st.markdown("Nasce ***Alan Jardine***, músico americano.")
                st.image("jardine.jpg")
                st.subheader("1943:")
                st.markdown("Nasce ***Mário Juruna***, líder indígena e político brasileiro. (m. 2002)")
                st.image("juruna.jpg")
                st.subheader("1946:")
                st.markdown("Nasce ***Dirceu Lopes***, futebolista brasileiro.")
                st.image("dirceu.jpg")
                st.subheader("1949:")
                st.markdown("Nasce ***José Pékerman***, treinador argentino de futebol.")
                st.image("pekerman.jpg")
            if SegundaMetade:
                st.subheader("1955:")
                st.markdown("Nasce ***Serginho Leite***, músico, humorista e locutor brasileiro. (m. 2011)")
                st.image("leite.jpg")
                st.subheader("1960:")
                st.markdown("Nasce ***Perry Bamonte***, músico britanico.")
                st.image("bamonte.jpg")
                st.subheader("1963:")
                st.markdown("Nasce ***Amber Lynn***, atriz *pornográfica* estadunidense.")
                st.image("lynn.jpg")
                st.subheader("1964:")
                st.markdown("Nasce ***Adam Curry***, empresário estadunidense.")
                st.image("curry.jpg")
                st.markdown("Nasce ***Gisele Froés***, atriz brasileira.")
                st.image("froes.jpg")
                st.subheader("1965:")
                st.markdown("Nasce ***Charlie Sheen***, ator estadunidense.")
                st.image("sheen.jpg")
                st.markdown("Nasce ***Carlos Eugênio Simon***, árbitro de futebol brasileiro.")
                st.image("simon.jpg")
                st.subheader("1969:")
                st.markdown("Nasce ***Jörg Müller***, piloto de automóveis alemão.")
                st.image("muller.jpg")
                st.subheader("1970:")
                st.markdown("Nasce ***Gareth Southgate***, futebolista e treinador britanico de futebol.")
                st.image("southgate.jpg")
                st.subheader("1971:")
                st.markdown("Nasce ***Luciano Huck***, apresentador de televisão brasileiro.")
                st.image("huck.jpg")
                st.markdown("Nasce ***Paolo Montero***, futebolista uruguaio.")
                st.image("montero.jpg")
                st.markdown("Nasce ***Emerson Ferretti***, futebolista brasilero.")
                st.image("ferretti.jpg")
                st.subheader("1973:")
                st.markdown("Nasce ***Jennifer Paige***, cantora estadunidense.")
                st.image("paige.jpg")
                st.subheader("1974:")
                st.markdown("Nasce ***Didier André***, piloto de automóveis francês.")
                st.image("didier.jpg" , caption="Didier André no seu Gran Turismo")
                st.subheader("1979:")
                st.markdown("Nasce ***Júlio César***, futebolista brasileiro.")
                st.image("julio.jpg")
                st.markdown("Nasce ***Tomo Miličević***, guitarrista croata.")
                st.image("tomo.jpg")
                st.subheader("1980:")
                st.markdown("Nasce ***Daniel Bilos***, futebolista argentino.")
                st.image("bilos.jpg")
                st.markdown("Nasce ***Lauro***, futebolista brasileiro.")
                st.image("lauro.jpg")
                st.subheader("1982:")
                st.markdown("Nasce ***Leo Lins***, humorista brasileiro.")
                st.image("lins.jpg")
                st.markdown("Nasce ***Thammy Miranda***, ator, repórter e político brasileiro.")
                st.image("thammy.jpg")
                st.subheader("1983:")
                st.markdown("Nasce ***Augusto Farfus***, piloto de automóveis brasileiro.")
                st.image("farfus.jpg")
                st.subheader("1984:")
                st.markdown("Nasce ***Garrett Hedlund***, ator estadunidense.")
                st.image("hedlund.jpg")
                st.subheader("1985:")
                st.markdown("Nasce ***Scott Carson***, futebolista britanico.")
                st.image("carson.jpg")
                st.markdown("Nasce ***Leandro Carrijo***, futebolista brasileiro.")
                st.image("carrijo.jpg")
                st.subheader("1986:")
                st.markdown("Nasce ***Leandro Franco da Rocha***, músico brasileiro.")
                st.image("franco.jpg")
                st.subheader("1988:")
                st.markdown("Nasce ***Carla Suárez Navarro***, tenista espanhola.")
                st.image("navarro.jpg")
                st.subheader("1989:")
                st.markdown("Nasce ***Bianca Bin***, atriz brasileira.")
                st.image("bin.jpg")
                st.markdown("Nasce ***Iza***, cantora e compositora brasileira.")
                st.image("iza.jpg")
                st.markdown("Nasce ***Rita Volk***, atriz estadunidense.")
                st.image("volk.jpg")
                st.subheader("1991:")
                st.markdown("Nasce ***Maurício Destri***, ator brasileiro.")
                st.image("destri.jpg")
                st.subheader("1993:")
                st.markdown("Nasce ***Lee Sung-jong***, cantor sul-coreano.")
                st.image("jong.jpg")
                st.markdown("Nasce ***Lee So-jung***, cantora sul-coreana.")
                st.image("jung.jpg")
                st.subheader("1996:")
                st.markdown("Nasce ***Joy***, cantora sul-coreana.")
                st.image("joy.jpg")
                st.subheader("1997:")
                st.markdown("Nasce ***Victor Meyniel***, ator, humorista e ex-youtuber brasileiro.")
                st.image("meyniel.jpg")
                st.subheader("1998:")
                st.markdown("Nasce ***Kanaphan Puitrakul***, ator, modelo e apresentador tailandês.")
                st.image("puitrakul.jpg")
                st.subheader("1999:")
                st.markdown("Nasce ***Rich Brian***, rapper chinês.")
                st.image("rich.jpg")
        if SeculoXXI and condition == True:
            st.subheader("2001:")
            st.markdown("Nasce ***Kata Blanka Vas***, desportista húngara.")
            st.image("blanka.jpg")
            st.subheader("2007:")
            st.markdown("Nasce ***Maria Coelho Santos***, estudante portuguesa.")
            st.image("maria.jpg")
            AcessoAreaSecreta = st.popover("Aceder à Área Secreta")
            with AcessoAreaSecreta:
               animal = st.text_input("Qual é o teu animal de estimação preferido?")
               animal_lower = animal.lower()
            if animal_lower in ["gato", "gatos", "gata", "gatas"]:
              col1, col2,  col3 = st.columns(3)
              col1.metric("" , "" , "")
              col2.metric("" , 'Parabéns!' , "")
              col3.metric("" , "" , "")
              st.balloons()
              st.balloons()
              st.balloons()
              st.balloons()
    #Mortes:

#Mortes:
elif Mortes:
        st.subheader("Principais Mortes" , divider= "rainbow")
        #Estabelecer que épocas evidenciar:
        with st.sidebar:
            st.markdown("**Por favor, selecione as principais épocas a visualizar:**")
            AteSeculoXIX = st.toggle("Anteriores ao século XIX")
            SeculoXIX = st.toggle("Século XIX")
            SeculoXX = st.toggle("Século XX")
            SeculoXXI = st.toggle("Século XXI")
            TodasAsEpocas = st.toggle("Todas as épocas")
        if TodasAsEpocas:
            condition = False
            st.subheader("1338:")
            st.markdown("Morre ***Ana de Boémia***, *Duquesa* da Áustria. (n. 1323)")
            st.image("boemia.jpg")
            st.subheader("1632:")
            st.markdown("Morre ***Vicente de Santo António***, santo português. (n. 1550)")
            st.image("santo.jpg")
            st.subheader("1649:")
            st.markdown("Morre ***Duarte de Bragança***, militar português. (n. 1605)")
            st.image("bragança.jpg")
            st.subheader("1659:")
            st.markdown("Morre ***Oliver Cromwell***, político inglês. (n. 1599)")
            st.image("o_cromwell.jpg")
            st.subheader("1792:")
            st.markdown("Morre ***Maria Luísa***, *Princesa* de Lamballe. (n. 1749)")
            st.image("lamballe.jpg")
            st.subheader("1853:")
            st.markdown("Morre ***Auguste de Saint-Hilaire***, naturalista francês. (n. 1779)")
            st.image("auguste.jpg")
            st.subheader("1877:")
            st.markdown("Morre ***Adolphe Thiers***, político francês. (n. 1797)")
            st.image("thiers.jpg")
            st.subheader("1881:")
            st.markdown("Morre ***Ivan Turgenev***, ecritor russo. (n. 1818)")
            st.image("ivan.jpg")
            st.subheader("1962:")
            st.markdown("Morre ***Aldo Locatelli***, pintor *italo-brasileiro*. (n. 1915)")
            st.image("locatelli.jpg" , caption='"Retrato de Marina Moraes Pires" - Aldo Locatelli.')
            st.markdown('Morre ***Edward Estlin "E. E." Cummings***, poeta estadunidense. (n. 1894)')
            st.image("cummings.jpg")
            st.subheader("1980:")
            st.markdown("Morre ***Fabian von Schlabrendorff***, resitente alemão e opositor ao partido *nazi*. (n. 1907)")
            st.image("fabian.jpg")
            st.subheader("1982:")
            st.markdown("Morre ***Frederic Dannay***, escritor estadunidense. (n. 1982)")
            st.image("dannay.jpg")
            st.subheader("1991:")
            st.markdown("Morre ***Frank Capra***, cineasta estadunidense. (n. 1897)")
            st.image("capra.jpg")
            st.subheader("1996:")
            st.markdown("Morre ***Walter Forster***, ator de cinema e pioneiro na televisão brasileira. (n. 1917)")
            st.image("walter.jpg")
            st.subheader("2001:")
            st.markdown("Morre ***Thuy Trang***, atriz vietnamita. (n. 1973)")
            st.image("thuy.jpg")
            st.subheader("2005:")
            st.markdown("Morre ***Fernando Távora***, arquiteto português. (n. 1923)")
            st.image("tavora.jpg")
            st.subheader("2012:")
            st.markdown("Morre ***Michael Duncan***, ator estadunidense. (n. 1957)")
            st.image("duncan.jpg")
            st.markdown("Morre ***Sun Myung Moon***, líder religioso, escritor e empresário sul-coreano. (n. 1920)")
            st.image("sun.jpg")
            st.markdown("Morre ***Griselda Blanco***, *narcotraficante* colombiana. (n. 1943)")
            st.image("blanco.jpg")
            st.subheader("2014:")
            st.markdown("Morre ***Go Eun-bi***, cantora sul-coreana. (n. 1992)")
            st.image("go.jpg")
            st.subheader("2016:")
            st.markdown("Morre ***Jean-Christophe Yoccoz***, matemático francês. (n. 1956)")
            st.image("yoccoz.jpg")
            st.subheader("2021:")
            st.markdown("Morre ***Sérgio Mamberti***, ator, diretor, produtor, artista plástico e político brasileiro. (n. 1939)")
            st.image("mamberti.jpg")
        if AteSeculoXIX and condition == True:
            st.subheader("1338:")
            st.markdown("Morre ***Ana de Boémia***, *Duquesa* da Áustria. (n. 1323)")
            st.image("boemia.jpg")
            st.subheader("1632:")
            st.markdown("Morre ***Vicente de Santo António***, santo português. (n. 1550)")
            st.image("santo.jpg")
            st.subheader("1649:")
            st.markdown("Morre ***Duarte de Bragança***, militar português. (n. 1605)")
            st.image("bragança.jpg")
            st.subheader("1659:")
            st.markdown("Morre ***Oliver Cromwell***, político inglês. (n. 1599)")
            st.image("o_cromwell.jpg")
            st.subheader("1792:")
            st.markdown("Morre ***Maria Luísa***, *Princesa* de Lamballe. (n. 1749)")
            st.image("lamballe.jpg")
        if SeculoXIX and condition == True:
            st.subheader("1853:")
            st.markdown("Morre ***Auguste de Saint-Hilaire***, naturalista francês. (n. 1779)")
            st.image("auguste.jpg")
            st.subheader("1877:")
            st.markdown("Morre ***Adolphe Thiers***, político francês. (n. 1797)")
            st.image("thiers.jpg")
            st.subheader("1881:")
            st.markdown("Morre ***Ivan Turgenev***, ecritor russo. (n. 1818)")
            st.image("ivan.jpg")
        if SeculoXX and condition == True:
            st.subheader("1962:")
            st.markdown("Morre ***Aldo Locatelli***, pintor *italo-brasileiro*. (n. 1915)")
            st.image("locatelli.jpg" , caption='"Retrato de Marina Moraes Pires" - Aldo Locatelli.')
            st.markdown('Morre ***Edward Estlin "E. E." Cummings***, poeta estadunidense. (n. 1894)')
            st.image("cummings.jpg")
            st.subheader("1980:")
            st.markdown("Morre ***Fabian von Schlabrendorff***, resitente alemão e opositor ao partido *nazi*. (n. 1907)")
            st.image("fabian.jpg")
            st.subheader("1982:")
            st.markdown("Morre ***Frederic Dannay***, escritor estadunidense. (n. 1982)")
            st.image("dannay.jpg")
            st.subheader("1991:")
            st.markdown("Morre ***Frank Capra***, cineasta estadunidense. (n. 1897)")
            st.image("capra.jpg")
            st.subheader("1996:")
            st.markdown("Morre ***Walter Forster***, ator de cinema e pioneiro na televisão brasileira. (n. 1917)")
            st.image("walter.jpg")
        if SeculoXXI and condition == True:
            st.subheader("2001:")
            st.markdown("Morre ***Thuy Trang***, atriz vietnamita. (n. 1973)")
            st.image("thuy.jpg")
            st.subheader("2005:")
            st.markdown("Morre ***Fernando Távora***, arquiteto português. (n. 1923)")
            st.image("tavora.jpg")
            st.subheader("2012:")
            st.markdown("Morre ***Michael Duncan***, ator estadunidense. (n. 1957)")
            st.image("duncan.jpg")
            st.markdown("Morre ***Sun Myung Moon***, líder religioso, escritor e empresário sul-coreano. (n. 1920)")
            st.image("sun.jpg")
            st.markdown("Morre ***Griselda Blanco***, *narcotraficante* colombiana. (n. 1943)")
            st.image("blanco.jpg")
            st.subheader("2014:")
            st.markdown("Morre ***Go Eun-bi***, cantora sul-coreana. (n. 1992)")
            st.image("go.jpg")
            st.subheader("2016:")
            st.markdown("Morre ***Jean-Christophe Yoccoz***, matemático francês. (n. 1956)")
            st.image("yoccoz.jpg")
            st.subheader("2021:")
            st.markdown("Morre ***Sérgio Mamberti***, ator, diretor, produtor, artista plástico e político brasileiro. (n. 1939)")
            st.image("mamberti.jpg")

